name: Deploy Frontend to Azure

on:
  push:
    branches:
      - main
    paths:
      - 'Frontend/**'
  workflow_dispatch:

env:
  NODE_VERSION: '20.x'
  AZURE_WEBAPP_FRONTEND_NAME: 'budget-tool-frontend'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: './Frontend/package-lock.json'

    - name: Install Frontend Dependencies
      working-directory: ./Frontend
      run: npm install --legacy-peer-deps
    
    - name: Build Frontend
      working-directory: ./Frontend
      run: npm run build

    - name: Copy web.config to dist
      working-directory: ./Frontend
      run: Copy-Item web.config dist/

    - name: Prepare Frontend for Deployment
      working-directory: ./Frontend
      run: |
        Copy-Item package.json dist/
        Copy-Item package-lock.json dist/
        New-Item -Path dist/server.js -ItemType File -Value @'
        const express = require('express');
        const path = require('path');
        const app = express();
        const port = process.env.PORT || 3000;
        
        app.use(express.static(path.join(__dirname)));
        
        app.get('*', (req, res) => {
          res.sendFile(path.join(__dirname, 'index.html'));
        });
        
        app.listen(port, () => {
          console.log(`Server running on port ${port}`);
        });
        '@
    
    - name: Install Express for Server
      working-directory: ./Frontend/dist
      run: npm install express --save
      
    - name: Zip Frontend Artifact
      working-directory: ./Frontend
      run: |
        Compress-Archive -Path dist/* -DestinationPath frontend-deploy.zip -Force
      
    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4A72AE0249ED4026BC6AE1953F51C3CF }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_84747220A89A4ABA929882948E7DD949 }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_25ADDA71426C444CBCB32D8CCFB743A8 }}

    - name: Deploy Frontend to Azure
      id: deploy-frontend
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_FRONTEND_NAME }}
        slot-name: 'Production'
        package: ./Frontend/frontend-deploy.zip
        
    - name: Logout from Azure
      run: az logout
      if: always() 